#!/usr/bin/env python3
"""No-Code Visual Agent Builder with Gradio.

Features:
- Drag-and-drop agent builder
- Visual workflow editor
- Pre-built templates
- One-click deployment
"""

import gradio as gr
import json
from typing import Any, Optional
from dataclasses import dataclass, asdict


@dataclass
class AgentNode:
    """Represents an agent node in the workflow."""
    id: str
    type: str  # "llm", "skill", "condition", "loop", "output"
    name: str
    config: dict
    position: tuple[int, int]


@dataclass
class WorkflowEdge:
    """Represents a connection between nodes."""
    source: str
    target: str
    label: str = ""


class WorkflowBuilder:
    """Builds agent workflows from visual configuration."""
    
    def __init__(self):
        self.nodes: list[AgentNode] = []
        self.edges: list[WorkflowEdge] = []
    
    def add_node(self, node_type: str, name: str, config: dict) -> str:
        """Add a node to the workflow."""
        import uuid
        node_id = str(uuid.uuid4())[:8]
        
        node = AgentNode(
            id=node_id,
            type=node_type,
            name=name,
            config=config,
            position=(0, 0),
        )
        
        self.nodes.append(node)
        return node_id
    
    def connect(self, source_id: str, target_id: str, label: str = "") -> None:
        """Connect two nodes."""
        self.edges.append(WorkflowEdge(
            source=source_id,
            target=target_id,
            label=label,
        ))
    
    def to_python_code(self) -> str:
        """Generate Python code from workflow."""
        lines = [
            "# Auto-generated by Piranha No-Code Builder",
            "from piranha import Agent, Task, Skill",
            "",
            "# Create agent",
            'agent = Agent(name="visual-agent", model="ollama/llama3:latest")',
            "",
            "# Workflow steps",
        ]
        
        # Sort nodes by position (top to bottom)
        sorted_nodes = sorted(self.nodes, key=lambda n: n.position[1])
        
        for i, node in enumerate(sorted_nodes):
            if node.type == "llm":
                lines.append(f"# Step {i+1}: {node.name}")
                prompt = node.config.get("prompt", "Process this")
                lines.append(f'result_{node.id} = agent.chat("{prompt}")')
            
            elif node.type == "skill":
                skill_name = node.config.get("skill", "unknown")
                lines.append(f"# Step {i+1}: Use {skill_name} skill")
                lines.append(f'skill_result_{node.id} = {skill_name}()')
            
            elif node.type == "condition":
                condition = node.config.get("condition", "True")
                lines.append(f"# Step {i+1}: Condition check")
                lines.append(f"if {condition}:")
                lines.append("    # Execute conditional branch")
            
            elif node.type == "output":
                lines.append(f"# Step {i+1}: Output")
                lines.append(f'print(f"Result: {{result_{node.id}}}")')
        
        return "\n".join(lines)
    
    def to_json(self) -> str:
        """Export workflow as JSON."""
        return json.dumps({
            "nodes": [asdict(n) for n in self.nodes],
            "edges": [asdict(e) for e in self.edges],
        }, indent=2)
    
    @classmethod
    def from_json(cls, json_str: str) -> "WorkflowBuilder":
        """Import workflow from JSON."""
        data = json.loads(json_str)
        
        builder = cls()
        
        for node_data in data["nodes"]:
            node = AgentNode(**node_data)
            builder.nodes.append(node)
        
        for edge_data in data["edges"]:
            edge = WorkflowEdge(**edge_data)
            builder.edges.append(edge)
        
        return builder


# Pre-built templates
TEMPLATES = {
    "Basic Chat": {
        "description": "Simple chat agent",
        "nodes": [
            {"type": "llm", "name": "Chat", "config": {"prompt": "Help the user"}},
        ],
    },
    "Research Assistant": {
        "description": "Research with web search",
        "nodes": [
            {"type": "llm", "name": "Understand Query", "config": {"prompt": "Analyze the research query"}},
            {"type": "skill", "name": "Web Search", "config": {"skill": "web_search"}},
            {"type": "llm", "name": "Synthesize", "config": {"prompt": "Summarize research findings"}},
            {"type": "output", "name": "Output", "config": {}},
        ],
        "edges": [
            {"source": "0", "target": "1"},
            {"source": "1", "target": "2"},
            {"source": "2", "target": "3"},
        ],
    },
    "Code Reviewer": {
        "description": "Review and improve code",
        "nodes": [
            {"type": "llm", "name": "Analyze Code", "config": {"prompt": "Review this code"}},
            {"type": "skill", "name": "Code Review", "config": {"skill": "code_review"}},
            {"type": "condition", "name": "Has Issues?", "config": {"condition": "issues_found"}},
            {"type": "llm", "name": "Suggest Fixes", "config": {"prompt": "Suggest improvements"}},
            {"type": "output", "name": "Output Review", "config": {}},
        ],
    },
    "Data Analyst": {
        "description": "Analyze CSV data",
        "nodes": [
            {"type": "skill", "name": "Load CSV", "config": {"skill": "csv-data-summarizer"}},
            {"type": "llm", "name": "Generate Insights", "config": {"prompt": "Find patterns in data"}},
            {"type": "skill", "name": "Create Chart", "config": {"skill": "statistical_analysis"}},
            {"type": "output", "name": "Report", "config": {}},
        ],
    },
}


def create_builder_ui():
    """Create the No-Code Builder UI."""
    
    with gr.Blocks(title="Piranha No-Code Agent Builder", theme=gr.themes.Soft()) as ui:
        gr.Markdown("""
        # 🛠️ Piranha No-Code Agent Builder
        
        Build AI agents visually without writing code!
        
        **Features:**
        - 🎨 Drag-and-drop workflow builder
        - 📦 Pre-built templates
        - 🐍 Auto-generate Python code
        - 🚀 One-click deployment
        """)
        
        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### 📦 Templates")
                
                template_names = list(TEMPLATES.keys())
                template_dropdown = gr.Dropdown(
                    choices=template_names,
                    label="Select Template",
                    value=template_names[0] if template_names else None,
                )
                
                template_info = gr.Textbox(
                    label="Template Description",
                    lines=2,
                    interactive=False,
                )
                
                load_template_btn = gr.Button("Load Template", variant="primary")
                
                gr.Markdown("---")
                
                gr.Markdown("### ➕ Add Node")
                
                node_type = gr.Radio(
                    choices=["llm", "skill", "condition", "loop", "output"],
                    label="Node Type",
                    value="llm",
                )
                
                node_name = gr.Textbox(
                    label="Node Name",
                    placeholder="e.g., Analyze Input",
                )
                
                node_config = gr.Textbox(
                    label="Configuration (JSON)",
                    placeholder='{"prompt": "Your prompt here"}',
                    lines=3,
                )
                
                add_node_btn = gr.Button("Add Node", variant="secondary")
                
                gr.Markdown("---")
                
                gr.Markdown("### 🔗 Connect Nodes")
                
                with gr.Row():
                    source_node = gr.Dropdown(
                        choices=[],
                        label="From Node",
                    )
                    target_node = gr.Dropdown(
                        choices=[],
                        label="To Node",
                    )
                
                edge_label = gr.Textbox(
                    label="Connection Label (optional)",
                    placeholder="e.g., on_success",
                )
                
                connect_btn = gr.Button("Connect Nodes", variant="secondary")
            
            with gr.Column(scale=2):
                gr.Markdown("### 🎨 Workflow Canvas")
                
                workflow_canvas = gr.JSON(
                    label="Workflow",
                    value={"nodes": [], "edges": []},
                )
                
                with gr.Row():
                    export_json_btn = gr.Button("Export JSON", variant="secondary")
                    export_python_btn = gr.Button("Export Python", variant="secondary")
                    deploy_btn = gr.Button("🚀 Deploy Agent", variant="primary")
                
                gr.Markdown("---")
                
                gr.Markdown("### 📄 Generated Code")
                
                generated_code = gr.Code(
                    label="Python Code",
                    language="python",
                    lines=15,
                )
            
            with gr.Column(scale=1):
                gr.Markdown("### 📋 Node List")
                
                node_list = gr.JSON(
                    label="Current Nodes",
                    value=[],
                )
                
                gr.Markdown("---")
                
                gr.Markdown("### ⚙️ Agent Settings")
                
                agent_name = gr.Textbox(
                    label="Agent Name",
                    value="my-visual-agent",
                )
                
                agent_model = gr.Dropdown(
                    choices=[
                        "ollama/llama3:latest",
                        "gpt-4",
                        "claude-3-5-sonnet",
                        "gemini-pro",
                    ],
                    label="LLM Model",
                    value="ollama/llama3:latest",
                )
                
                agent_description = gr.Textbox(
                    label="Description",
                    lines=2,
                    placeholder="What does your agent do?",
                )
        
        # State
        workflow_state = gr.State(WorkflowBuilder())
        
        # Event handlers
        def update_template_info(selected):
            if selected and selected in TEMPLATES:
                return TEMPLATES[selected]["description"]
            return ""
        
        def load_template(selected, state: WorkflowBuilder):
            if not selected or selected not in TEMPLATES:
                return state, [], {}, "Select a template"
            
            template = TEMPLATES[selected]
            state = WorkflowBuilder()
            
            node_ids = []
            for i, node_data in enumerate(template.get("nodes", [])):
                node_id = state.add_node(
                    node_type=node_data["type"],
                    name=node_data["name"],
                    config=node_data.get("config", {}),
                )
                node_ids.append((node_id, node_data["name"]))
            
            for edge_data in template.get("edges", []):
                if edge_data["source"] < len(node_ids) and edge_data["target"] < len(node_ids):
                    state.connect(
                        node_ids[int(edge_data["source"])][0],
                        node_ids[int(edge_data["target"])][0],
                        edge_data.get("label", ""),
                    )
            
            node_choices = [f"{nid} - {name}" for nid, name in node_ids]
            
            return (
                state,
                node_choices,
                {"nodes": len(state.nodes), "edges": len(state.edges)},
                state.to_python_code(),
            )
        
        def add_node(node_type, name, config_json, state: WorkflowBuilder):
            try:
                config = json.loads(config_json) if config_json else {}
            except json.JSONDecodeError:
                return state, [], "Invalid JSON in config", []
            
            if not name:
                return state, [], "Node name is required", []
            
            node_id = state.add_node(node_type, name, config)
            
            node_choices = [f"{n.id} - {n.name}" for n in state.nodes]
            node_list = [{"id": n.id, "type": n.type, "name": n.name} for n in state.nodes]
            
            return (
                state,
                node_choices,
                f"✓ Added node: {name} ({node_id})",
                node_list,
            )
        
        def connect_nodes(source, target, label, state: WorkflowBuilder):
            if not source or not target:
                return state, "Select both source and target nodes"
            
            source_id = source.split(" - ")[0]
            target_id = target.split(" - ")[0]
            
            state.connect(source_id, target_id, label)
            
            return state, f"✓ Connected {source_id} → {target_id}"
        
        def export_workflow_json(state: WorkflowBuilder):
            return state.to_json()
        
        def export_workflow_python(state: WorkflowBuilder, name, model):
            code = state.to_python_code()
            
            # Update agent settings
            code = code.replace('name="visual-agent"', f'name="{name}"')
            code = code.replace('model="ollama/llama3:latest"', f'model="{model}"')
            
            return code
        
        def deploy_agent(state: WorkflowBuilder, name, model, description):
            """Generate deployment-ready agent code."""
            code = f'''#!/usr/bin/env python3
"""Auto-generated Agent: {name}

{description or "No description"}
"""

from piranha import Agent, Task

# Create agent
agent = Agent(
    name="{name}",
    model="{model}",
    description="{description or ""}",
)

# Workflow execution
'''
            code += state.to_python_code()
            code += '''

if __name__ == "__main__":
    print(f"✓ Agent '{agent.name}' deployed successfully!")
'''
            return code
        
        # Wire up events
        template_dropdown.change(
            fn=update_template_info,
            inputs=[template_dropdown],
            outputs=[template_info],
        )
        
        load_template_btn.click(
            fn=load_template,
            inputs=[template_dropdown, workflow_state],
            outputs=[workflow_state, source_node, workflow_canvas, generated_code],
        )
        
        add_node_btn.click(
            fn=add_node,
            inputs=[node_type, node_name, node_config, workflow_state],
            outputs=[workflow_state, source_node, gr.Textbox(label="Status"), node_list],
        )
        
        connect_btn.click(
            fn=connect_nodes,
            inputs=[source_node, target_node, edge_label, workflow_state],
            outputs=[workflow_state, gr.Textbox(label="Status")],
        )
        
        export_json_btn.click(
            fn=export_workflow_json,
            inputs=[workflow_state],
            outputs=[generated_code],
        )
        
        export_python_btn.click(
            fn=export_workflow_python,
            inputs=[workflow_state, agent_name, agent_model],
            outputs=[generated_code],
        )
        
        deploy_btn.click(
            fn=deploy_agent,
            inputs=[workflow_state, agent_name, agent_model, agent_description],
            outputs=[generated_code],
        )
    
    return ui


if __name__ == "__main__":
    ui = create_builder_ui()
    ui.launch(
        server_name="0.0.0.0",
        server_port=7861,
        inbrowser=True,
    )
